### ISSUE TITLE
 ERROR: /usr/lib/vdr/plugins/libvdr-xineliboutput.so.2.2.0: undefined symbol: _Z13x_avahi_startiii

### ISSUE THREAD

**Issue by tinitussi** [VDR4Arch/vdr4arch#153]
Hallo,
da ist ein Problem mit xineliboutput:

 ERROR: /usr/lib/vdr/plugins/libvdr-xineliboutput.so.2.2.0: undefined symbol: _Z13x_avahi_startiii

Deshalb startet der VDR nicht durch. Grüße

**Comment by knedlyk** [comment]
I have the same issue.

**Comment by CReimer** [comment]
@M-Reimer fixed this a few days ago. I forgot to compile the new changes for the binary repository. This should be fixed.

**Comment by knedlyk** [comment]
Hm, it is not fixed, at least for me. I installed new packages form the repo and got the same errror.
vdr4arch/xineliboutput-frontends 1.1.0.119.g2889fd9-2 [installed]
vdr4arch/xineliboutput-xineplug 1.1.0.119.g2889fd9-2 [installed]

[1677] ERROR: /usr/lib/vdr/plugins/libvdr-xineliboutput.so.2.2.0: undefined symbol: _Z13x_avahi_startiii.

Did you update you repos?
BTW, in master branch of vdr4arch, i.e. for vdr=2.2.0, in xineliboutput PKGBUILD you have vdr-api=2.3.2 instead of 2.2.0.

**Comment by CReimer** [comment]
master branch? There's no master branch in vdr4arch. There are two branches vdr-stable and vdr-next.

**Comment by tinitussi** [comment]
Same Problem here.
ERROR: /usr/lib/vdr/plugins/libvdr-xineliboutput.so.2.2.0: undefined symbol: _Z13x_avahi_startiii

**Comment by knedlyk** [comment]
Mea culpa, I checked vdr-next by mistake.

**Comment by CReimer** [comment]
Just tried it myself. The error is there. I'll try to find a workaround.

**Comment by tinitussi** [comment]
No Problem. Thanks for your work!

**Comment by CReimer** [comment]
Please try again. It should be fixed now.

**Comment by knedlyk** [comment]
Fixed. No errors.
